### ISSUE TITLE
make-dot.py fails

### ISSUE THREAD

**Issue by eero-t** [clearlinux/clr-bundles#101]
**Actual outcome**

```
$ python3 ./make-dot.py 
Traceback (most recent call last):
  File "./make-dot.py", line 92, in <module>
    main()
  File "./make-dot.py", line 13, in main
    edges = generate_edges(bundledict)
  File "./make-dot.py", line 59, in generate_edges
    includebundle = bundledict[includename]
KeyError: 'iproute2'
```
While "iproute2" bundle/package is referred:
```
$ git grep iproute2
bundles/cloud-native-basic:include(iproute2)
bundles/clr-installer:include(iproute2)
bundles/containers-basic:include(iproute2)
bundles/desktop-dev:include(iproute2)
bundles/network-basic:include(iproute2)
bundles/network-basic-dev:include(iproute2)
bundles/os-clr-on-clr-dev:include(iproute2)
bundles/os-core:iproute2-bin
bundles/os-core-dev:iproute2-dev
bundles/os-installer:include(iproute2)
bundles/performance-tools:include(iproute2)
bundles/sysadmin-basic:include(iproute2)
bundles/user-basic-dev:include(iproute2)
packages:iproute2 # utilities for controlling TCP / IP networking and traffic control
```

There's no such bundle:
```
$ find -name '*iproute2*'
$ git pull
Already up-to-date.
```

**Expected outcome**

If bundle/package dependencies are broken, this tools should tell that things are broken and show it in the dependency graph.

See also #49.

**Comment by ahkok** [comment]
The tool was never designed to handle `pundles` and is outdated. This is not a dependency checking tool, either.

**Comment by eero-t** [comment]
> The tool was never designed to handle pundles and is outdated.

If it's not supposed to work anymore, shouldn't it be removed from repo & readme?

> This is not a dependency checking tool, either.

Thanks for the fast reply!

I was hoping for more usable tool for investigating the system / bundle content than swupd:
* https://github.com/clearlinux/swupd-client/issues/806
* https://github.com/clearlinux/swupd-client/issues/807

(If it works everywhere and doesn't necessarily need a working ClearLinux installation, that's a bonus.  Debian/Ubuntu have www-site providing package search results and dep diagrams.)

**Comment by ahkok** [comment]
> If it's not supposed to work anymore, shouldn't it be removed from repo & readme? 

Nope, it just needs to be fixed again. :)

@bryteise

**Comment by phmccarty** [comment]
Working on a fix. I will post the patch shortly.

**Comment by phmccarty** [comment]
Patch posted: https://lists.clearlinux.org/pipermail/dev/2019-February/002495.html

**Comment by eero-t** [comment]
Patch fixes the exception, but the resulting graph is such a mess that it's useless.  There are so much overlapping arrows that it's impossible to see why that happens.  Should the script be removing all the indirect dependencies? 

PS. I prefer XDot (on debian/ubuntu, in "xdot" package) for viewing dot graphs.  It's much nicer than "dotty" or any of the SVG viewers I've used (most SVG viewers limit max zoom level to something where large graphs aren't even readable).

**Comment by eero-t** [comment]
There's a commit fixing the initial exception, but the tool throws also exception if bundles directory has anything else than bundle files.  I had there a tmp/ directory, and it tried to parse that as bundle file.  That's fine though, the main issue that its output isn't readable.

Removing dependencies that are satisfied through immediate dependencies should make the graph readable, but  I don't see this script doing it.
