### ISSUE TITLE
make-dot.py can't run normally to build the graph of bundle dependency

### ISSUE THREAD

**Issue by gaoethan** [clearlinux/clr-bundles#49]
Tried to run `make-dot.py` to create the dependency graph of clearlinux bundles, but the following error occurs.

```
ros@ros2clr ~/workspace/clr/clr-bundles $ ls
auto.devbundles  bundle-header.txt  bundles  make-dot.py  packages  README.md
ros@ros2clr ~/workspace/clr/clr-bundles $ python3 make-dot.py | dot -Tsvg > dot.svg
Warning: Could not load "/usr/lib64/graphviz/libgvplugin_pango.so.6" - file not found
Traceback (most recent call last):
  File "make-dot.py", line 86, in <module>
    main()
  File "make-dot.py", line 13, in main
    edges = generate_edges(bundledict)
  File "make-dot.py", line 53, in generate_edges
    includebundle = bundledict[includename]
KeyError: 'p11-kit'
ros@ros2clr ~/workspace/clr/clr-bundles $ 

```

**Comment by mrkz** [comment]
@bryteise  Any idea?

**Comment by bryteise** [comment]
Hrm so I haven't touched this and I don't do validation for the script. I'm see about getting it to work again.

**Comment by bryteise** [comment]
Okay, so I have this fixed and it should be in the next release.
