### ISSUE TITLE
Certbot failure

### ISSUE THREAD

**Issue by aravindet** [clearlinux/clr-bundles#56]
On a new AWS EC2 Instance created using the Clear Linux AMI from Amazon Marketplace, I ran:

```
sudo swupd install nginx certbot
sudo swupd update
sudo certbot --help
```
and got
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mock' distribution was not found and is required by certbot
```

All certbot commands, with and without sudo, produce the same error.

**Comment by ahkok** [comment]
can you list what bundles you have installed?
